# Site settings
title: Prawnsgame
email: prawnsgame@gmail.com
description: "A site for all the resourses, as well as the results from the WCGS Programming Society"
baseurl: "/"
url: "http://prawnsgame.org.uk"

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true
