# Site settings
title: Programming @ WCGS
email: sherd030@suttonlea.org
description: "A site for all the resourses, as well as the results from the WCGS Programming Society"
baseurl: "/"
url: "http://wcgs-programming.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true
